
import '../data.dart';
import 'evaluation.dart';



class Patient {
  //----Attributes -----------
  double _id; //automaticly generated by the system (unique)

  //1.attributes to be completed at inscription (obligatory): via le formulaire d'inscription /!\
  String name;
  String firstName;
  Gender gender;
  DateTime birthDate;
  String phoneNumber;
  //String email;

  //2.attributes to be completed (or automaticaly setted) after inscription (to do: implement getters and setters): modification via le "systeme Keepiin"
  String login;// automaticaly generated by the system
  String password;// automaticaly generated by the system  (must be crypted)
  //Tuple2<String,String> authentification; //Tuple2<login ,password>
  //Tuple2<AvcType,AvcPosition> avcDetails; //typePriseEnCharge
  DateTime dateOfLastAvc;
  List<String> autresDetails; //=> exemple:antécédents, en activité ou pas, vivant seul, etc...
  //List<Doctor> listOfDoctor;
  List<Evaluation> listEvaluation;
  //List<Tuple2<Exercice,DateTime>> listExercice;

  //---------- Constructor --------------

  Patient(  String name, String firstName,    Gender gender,   DateTime birthDate,
      //String email,
      String phoneNumber){
    // Formating 'name' to UpperCase and 'firstname' with le first letter in upperCase and the rest in lowerCase
    var _name = name.trim();
    var _firstName = firstName.trim();
    this.name = _name.toUpperCase();
    this.firstName = _firstName.substring(0, 1).toUpperCase() +_firstName.substring(1, _firstName.length).toLowerCase();
    this.gender = gender;
    this.birthDate = birthDate;
    //this.email= EmailValidator.validate(email) ? email : null ; //
    this.phoneNumber=phoneNumber;
  }

String getName(){return this.name;}

}

